apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodatapvc
  namespace: mongodb
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
