apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodbpv
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-sc-cinderplugin
