apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
    env: stg
    version: beta
  name: mongodbdeploy
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      env: stg
      version: beta
  strategy: {}
  template:
    metadata:
      labels:
        app: mongodb
        env: stg
        version: beta
    spec:
      containers:
      - image: registry.ficld.ir/mongo:7.0
        name: mongo
        args: ["--dbpath", "/data/db"]
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "4"
            memory: "4G"
        livenessProbe:
          exec:
            command:
            - mongo
            - --disableImplicitSessions
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --disableImplicitSessions
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodbsec
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodbsec
              key: password
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongodatad"
        persistentVolumeClaim:
          claimName: "mongodatapvc"
