apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: efk
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  type: ClusterIP  # Internal service for cluster communication