apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
spec:
  selector:
    app: fluentd
  ports:
  - protocol: TCP
    port: 24224  # Adjust port if needed (default Fluentd admin port)
    targetPort: 24224
  type: ClusterIP  # Cluster-internal access for troubleshooting