apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluentd-pv
  namespace: EFK
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/fluentd
  type: Local