apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-pv
  namespace: EFK
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kibana
  type: Local